In [ ]:
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

# Step 1: Select NSE stocks
stocks = ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ITC.NS']
start_date = '2023-01-01'
end_date = '2025-01-01'



In [ ]:
stocks = yf.download(stocks, start=start_date, end=end_date)['Close']

[*********************100%***********************]  5 of 5 completed


In [ ]:
stocks.reset_index(inplace=True)

In [ ]:
stocks

Ticker       Date  HDFCBANK.NS      INFY.NS      ITC.NS  RELIANCE.NS  \
0      2023-01-02  1588.541626  1459.632446  312.541962  1180.586060   
1      2023-01-03  1598.929199  1458.243774  310.898743  1171.946655   
2      2023-01-04  1570.351562  1431.665771  307.048828  1154.301392   
3      2023-01-05  1560.256836  1412.893677  313.105316  1152.239014   
4      2023-01-06  1555.087524  1387.321167  314.607666  1162.711548   
..            ...          ...          ...         ...          ...   
486    2024-12-24  1798.099976  1909.050049  478.450012  1222.750000   
487    2024-12-26  1790.750000  1907.400024  476.950012  1216.550049   
488    2024-12-27  1798.250000  1916.750000  478.600006  1221.050049   
489    2024-12-30  1777.900024  1906.000000  477.000000  1210.699951   
490    2024-12-31  1772.849976  1880.000000  483.649994  1215.449951   

Ticker       TCS.NS  
0       3167.366455  
1       3215.826904  
2       3219.031250  
3       3215.583984  
4       3118.905762  
..              ...  
486     4179.500000  
487     4169.100098  
488     4164.850098  
489     4158.799805  
490     4094.800049  

[491 rows x 6 columns]

In [ ]:
def hist_return(days):
    ''' It calculates Stock returns for various days and returns a dataframe.
        Input: Months in the form of a list.
        Output: Historical returns in the form of a DataFrame. '''
    idx=[]
    df=pd.DataFrame()
    for mon in days:
        temp=-(stocks.iloc[0,1:] - stocks.iloc[mon,1:])/(stocks.iloc[0,1:])
        idx.append(str(mon)+'_day_return')
        df=pd.concat([df, temp.to_frame().T], ignore_index=True)
    df.index=idx
    return df

In [ ]:
hist_stock_returns=hist_return([3*30,6*30,12*30,15*30,490])
hist_stock_returns

Ticker         HDFCBANK.NS   INFY.NS    ITC.NS RELIANCE.NS    TCS.NS
90_day_return     0.017523 -0.181824  0.304923    -0.05303 -0.013836
180_day_return   -0.049206 -0.019709   0.37131   -0.012129   0.11046
360_day_return     0.05279  0.034478  0.354378    0.216853  0.199321
450_day_return    0.092637  0.203899   0.56395    0.128296  0.252918
490_day_return    0.116024  0.287995  0.547472    0.029531  0.292809

In [ ]:
gene = np.random.rand()
gene

0.5431989751874234

In [ ]:
import time
def gen_mc_grid(rows, cols, n, N):  # , xfname): generate monte carlo wind farm layout grids
        np.random.seed(seed=int(time.time()))  # init random seed
        layouts = np.zeros((n, rows * cols), dtype=np.int32)  # one row is a layout
        # layouts_cr = np.zeros((n*, 2), dtype=np.float32)  # layouts column row index
        positionX = np.random.randint(0, cols, size=(N * n * 2))
        positionY = np.random.randint(0, rows, size=(N * n * 2))
        ind_rows = 0  # index of layouts from 0 to n-1
        ind_pos = 0  # index of positionX, positionY from 0 to N*n*2-1
        # ind_crs = 0
        while ind_rows < n:
            layouts[ind_rows, positionX[ind_pos] + positionY[ind_pos] * cols] = 1
            if np.sum(layouts[ind_rows, :]) == N:
                # for ind in range(rows * cols):
                #     if layouts[ind_rows, ind] == 1:
                #         r_i = np.floor(ind / cols)
                #         c_i = np.floor(ind - r_i * cols)
                #         layouts_cr[ind_crs, 0] = c_i
                #         layouts_cr[ind_crs, 1] = r_i
                #         ind_crs += 1
                ind_rows += 1
            ind_pos += 1
            if ind_pos >= N * n * 2:
                print("Not enough positions")
                break
        # filename = "positions{}by{}by{}N{}.dat".format(rows, cols, n, N)
#         np.savetxt(lofname, layouts, fmt='%d', delimiter="  ")
        # np.savetxt(xfname, layouts_cr, fmt='%d', delimiter="  ")
        return layouts

def gen_mc_grid_with_NA_loc(rows, cols, n, N,NA_loc):  # , xfname): generate monte carlo wind farm layout grids
        np.random.seed(seed=int(time.time()))  # init random seed
        layouts = np.zeros((n, rows * cols), dtype=np.int32)  # one row is a layout, NA loc is 0

        layouts_NA= np.zeros((n, rows * cols), dtype=np.int32)  # one row is a layout, NA loc is 2
        for i in NA_loc:
            layouts_NA[:,i-1]=2

        # layouts_cr = np.zeros((n*, 2), dtype=np.float32)  # layouts column row index
        positionX = np.random.randint(0, cols, size=(N * n * 2))
        positionY = np.random.randint(0, rows, size=(N * n * 2))
        ind_rows = 0  # index of layouts from 0 to n-1
        ind_pos = 0  # index of positionX, positionY from 0 to N*n*2-1
        # ind_crs = 0
        N_count=0
        while ind_rows < n:
            cur_state=layouts_NA[ind_rows, positionX[ind_pos] + positionY[ind_pos] * cols]
            if cur_state!=1 and cur_state!=2:
                layouts[ind_rows, positionX[ind_pos] + positionY[ind_pos] * cols]=1
                layouts_NA[ind_rows, positionX[ind_pos] + positionY[ind_pos] * cols] = 1
                N_count+=1
                if np.sum(layouts[ind_rows, :]) == N:
                    ind_rows += 1
                    N_count=0
            ind_pos += 1
            if ind_pos >= N * n * 2:
                print("Not enough positions")
                break
        # filename = "positions{}by{}by{}N{}.dat".format(rows, cols, n, N)
#         np.savetxt(lofname, layouts, fmt='%d', delimiter="  ")
#         np.savetxt(loNAfname, layouts_NA, fmt='%d', delimiter="  ")
        # np.savetxt(xfname, layouts_cr, fmt='%d', delimiter="  ")
        return layouts,layouts_NA

In [ ]:
gen_mc_grid(5, 5, 100, 50)
gen_mc_grid_with_NA_loc(5, 5, 100, 50,range(10))

Not enough positions
Not enough positions


(array([[0, 0, 0, ..., 1, 1, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32),
 array([[2, 2, 2, ..., 1, 1, 2],
        [2, 2, 2, ..., 0, 0, 2],
        [2, 2, 2, ..., 0, 0, 2],
        ...,
        [2, 2, 2, ..., 0, 0, 2],
        [2, 2, 2, ..., 0, 0, 2],
        [2, 2, 2, ..., 0, 0, 2]], dtype=int32))

In [ ]:
def chromosome(n):
    ''' Generates set of random numbers whose sum is equal to 1
        Input: Number of stocks.
        Output: Array of random numbers'''
    ch = np.random.rand(n)
    return ch/sum(ch)

In [ ]:
child=chromosome(5)
print(child,sum(child))

[0.3272947  0.15166915 0.22433824 0.06919676 0.22750116] 1.0


In [ ]:
n=5 # Number of stocks = 6
pop_size=100 # initial population = 100

population = np.array([chromosome(n) for _ in range(pop_size)])
print(population.shape)
print(population)

(100, 5)
[[2.36741119e-01 1.46232723e-01 2.70729067e-01 2.18013639e-01
  1.28283452e-01]
 [2.51596608e-01 2.29565779e-01 2.45777223e-01 1.87711952e-01
  8.53484391e-02]
 [1.06050185e-01 1.69795237e-01 2.64656026e-01 2.16445149e-01
  2.43053403e-01]
 [2.27326325e-01 2.12217388e-01 2.86988838e-02 2.61915288e-01
  2.69842116e-01]
 [2.26630949e-01 3.57135716e-02 2.71574301e-01 2.57829843e-01
  2.08251335e-01]
 [2.96274305e-01 2.25164825e-01 6.48211435e-02 1.53789176e-01
  2.59950552e-01]
 [2.52150921e-01 6.98174858e-02 2.35674138e-01 1.05452206e-01
  3.36905249e-01]
 [1.31615052e-01 1.96411936e-01 1.52682970e-01 3.74001250e-01
  1.45288792e-01]
 [1.49682599e-01 1.81554085e-01 2.48691399e-01 1.19276065e-01
  3.00795852e-01]
 [4.81681358e-02 3.71369639e-01 2.07266373e-02 3.47029721e-01
  2.12705867e-01]
 [2.85050204e-01 4.36172777e-01 2.71292464e-02 2.06467119e-01
  4.51806532e-02]
 [3.18295233e-01 3.07904753e-01 2.58701585e-01 4.53485254e-02
  6.97499036e-02]
 [2.22984495e-03 1.45049998e-01

In [ ]:
# Convert to numeric columns from Object datatypes.
print(hist_stock_returns.info())
cols=hist_stock_returns.columns
hist_stock_returns[cols] = hist_stock_returns[cols].apply(pd.to_numeric, errors='coerce')
print(hist_stock_returns.info())

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 90_day_return to 490_day_return
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   HDFCBANK.NS  5 non-null      object
 1   INFY.NS      5 non-null      object
 2   ITC.NS       5 non-null      object
 3   RELIANCE.NS  5 non-null      object
 4   TCS.NS       5 non-null      object
dtypes: object(5)
memory usage: 412.0+ bytes
None
<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 90_day_return to 490_day_return
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   HDFCBANK.NS  5 non-null      float64
 1   INFY.NS      5 non-null      float64
 2   ITC.NS       5 non-null      float64
 3   RELIANCE.NS  5 non-null      float64
 4   TCS.NS       5 non-null      float64
dtypes: float64(5)
memory usage: 412.0+ bytes
None


In [ ]:
cov_hist_return=hist_stock_returns.cov()

print(cov_hist_return)

# For ease of calculations make covariance of same variable as zero.
for i in range(5):
    cov_hist_return.iloc[i][i]=0

cov_hist_return

Ticker       HDFCBANK.NS   INFY.NS    ITC.NS  RELIANCE.NS    TCS.NS
Ticker                                                             
HDFCBANK.NS     0.004250  0.009245  0.005777     0.003051  0.005892
INFY.NS         0.009245  0.034512  0.020738     0.007978  0.022107
ITC.NS          0.005777  0.020738  0.014134     0.003023  0.012448
RELIANCE.NS     0.003051  0.007978  0.003023     0.012039  0.007902
TCS.NS          0.005892  0.022107  0.012448     0.007902  0.015036


<ipython-input-14-f810ca6f164b>:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  cov_hist_return.iloc[i][i]=0
<ipython-input-14-f810ca6f164b>:7: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version,

Ticker       HDFCBANK.NS   INFY.NS    ITC.NS  RELIANCE.NS    TCS.NS
Ticker                                                             
HDFCBANK.NS     0.000000  0.009245  0.005777     0.003051  0.005892
INFY.NS         0.009245  0.000000  0.020738     0.007978  0.022107
ITC.NS          0.005777  0.020738  0.000000     0.003023  0.012448
RELIANCE.NS     0.003051  0.007978  0.003023     0.000000  0.007902
TCS.NS          0.005892  0.022107  0.012448     0.007902  0.000000

In [ ]:
mean_hist_return=hist_stock_returns.mean()
mean_hist_return

Ticker
HDFCBANK.NS    0.045953
INFY.NS        0.064968
ITC.NS         0.428407
RELIANCE.NS    0.061904
TCS.NS         0.168334
dtype: float64

In [ ]:
sd_hist_return=hist_stock_returns.std()
sd_hist_return

Ticker
HDFCBANK.NS    0.065191
INFY.NS        0.185775
ITC.NS         0.118888
RELIANCE.NS    0.109722
TCS.NS         0.122621
dtype: float64

In [ ]:
def mean_portfolio_return(child):
    return np.sum(np.multiply(child,mean_hist_return))

In [ ]:
mean_portfolio_return(population[0])


0.17145204112745943

In [ ]:
def var_portfolio_return(child):
    part_1 = np.sum(np.multiply(child,sd_hist_return)**2)
    temp_lst=[]
    for i in range(5):
        for j in range(5):
            temp=cov_hist_return.iloc[i][j] * child[i] * child[j]
            temp_lst.append(temp)
    part_2=np.sum(temp_lst)
    return part_1+part_2

In [ ]:
var_portfolio_return(population[0])


<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


0.009528940092831843

In [ ]:
rf= 0.0697


In [ ]:
def fitness_fuction(child):
    ''' This will return the Sharpe ratio for a particular portfolio.
        Input: A child/chromosome (1D Array)
        Output: Sharpe Ratio value (Scalar)'''
    return (mean_portfolio_return(child)-rf)/np.sqrt(var_portfolio_return(child))

In [ ]:
fitness_fuction(population[7])


<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


0.6090504116041036

In [ ]:
def Select_elite_population(population, frac=0.3):
    ''' Select elite population from the total population based on fitness function values.
        Input: Population and fraction of population to be considered as elite.
        Output: Elite population.'''
    population = sorted(population,key = lambda x: fitness_fuction(x),reverse=True)
    percentage_elite_idx = int(np.floor(len(population)* frac))
    return population[:percentage_elite_idx]

In [ ]:
print(len(Select_elite_population(population, frac=0.3)))
Select_elite_population(population, frac=0.3)

<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


30


[array([0.09812373, 0.10520165, 0.47546635, 0.04955646, 0.27165181]),
 array([0.0900034 , 0.01805285, 0.40112246, 0.16721411, 0.32360719]),
 array([1.73859153e-02, 1.55620999e-04, 3.38494525e-01, 5.70546523e-02,
        5.86909286e-01]),
 array([0.01004624, 0.05777417, 0.397172  , 0.39449037, 0.14051722]),
 array([0.17609195, 0.02332591, 0.35431585, 0.04951955, 0.39674674]),
 array([0.25514386, 0.02115019, 0.3573052 , 0.0454423 , 0.32095845]),
 array([0.02280257, 0.14680225, 0.43746763, 0.36203824, 0.03088932]),
 array([0.39523768, 0.13413701, 0.4070629 , 0.04280661, 0.02075579]),
 array([0.10521773, 0.1189034 , 0.34335136, 0.09862497, 0.33390254]),
 array([0.1064532 , 0.02330907, 0.29638082, 0.27987871, 0.2939782 ]),
 array([0.18562364, 0.03987191, 0.28327912, 0.22294426, 0.26828107]),
 array([0.26658108, 0.03299043, 0.27511457, 0.20226439, 0.22304953]),
 array([0.40651202, 0.00191585, 0.25568668, 0.08624015, 0.24964531]),
 array([0.22663095, 0.03571357, 0.2715743 , 0.25782984, 0.2082

In [ ]:
[fitness_fuction(x) for x in population][:3]

<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


[1.042367426825165, 0.8493878593254367, 1.0556866092924937]

In [ ]:
def mutation(parent):
    ''' Randomy choosen elements of a chromosome are swapped
        Input: Parent
        Output: Offspring (1D Array)'''
    child=parent.copy()
    n=np.random.choice(range(5),2)
    while (n[0]==n[1]):
        n=np.random.choice(range(5),2)
    child[n[0]],child[n[1]]=child[n[1]],child[n[0]]
    return child

In [ ]:
mutation(population[1]),population[1]

(array([0.22956578, 0.25159661, 0.24577722, 0.18771195, 0.08534844]),
 array([0.25159661, 0.22956578, 0.24577722, 0.18771195, 0.08534844]))

In [ ]:
def Heuristic_crossover(parent1,parent2):
    ''' The offsprings are created according to the equation:
            Off_spring A = Best Parent  + β ∗ ( Best Parent − Worst Parent)
            Off_spring B = Worst Parent - β ∗ ( Best Parent − Worst Parent)
                Where β is a random number between 0 and 1.
        Input: 2 Parents
        Output: 2 Children (1d Array)'''
    ff1=fitness_fuction(parent1)
    ff2=fitness_fuction(parent2)
    diff=parent1 - parent2
    beta=np.random.rand()
    if ff1>ff2:
        child1=parent1 + beta * diff
        child2=parent2 - beta * diff
    else:
        child2=parent1 + beta * diff
        child1=parent2 - beta * diff
    return child1,child2

In [ ]:
for i in population[:30]:
    for j in population[:30]:
        print(Heuristic_crossover
              (i,j))

<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


(array([0.23674112, 0.14623272, 0.27072907, 0.21801364, 0.12828345]), array([0.23674112, 0.14623272, 0.27072907, 0.21801364, 0.12828345]))
(array([0.22454491, 0.0778171 , 0.29121429, 0.24289103, 0.16353268]), array([0.26379282, 0.2979814 , 0.225292  , 0.16283456, 0.05009921]))
(array([0.06509076, 0.17717989, 0.26275269, 0.21595357, 0.27902308]), array([0.27770054, 0.13884807, 0.2726324 , 0.21850521, 0.09231377]))
(array([0.24092501, 0.11690944, 0.37828616, 0.19850395, 0.06537544]), array([ 0.22314243,  0.24154067, -0.07885821,  0.28142498,  0.33275013]))
(array([ 0.216918  , -0.07046339,  0.27238633,  0.29608171,  0.28507736]), array([0.24645407, 0.25240969, 0.26991704, 0.17976177, 0.05145743]))
(array([0.21112438, 0.11226875, 0.35932991, 0.24564901, 0.07162795]), array([ 0.32189105,  0.2591288 , -0.0237797 ,  0.12615381,  0.31660605]))
(array([0.2631706 , 0.01517229, 0.21060606, 0.02495855, 0.4860925 ]), array([ 0.22572144,  0.20087792,  0.29579715,  0.29850729, -0.0209038 ]))
(array(

In [ ]:
def Arithmetic_crossover(parent1,parent2):
    ''' The offsprings are created according to the equation:
            Off spring A = α ∗ Parent1 + (1 −α) ∗ Parent2
            Off spring B = (1 −α) ∗ Parent1 + α ∗ Parent2

                Where α is a random number between 0 and 1.
        Input: 2 Parents
        Output: 2 Children (1d Array)'''
    alpha = np.random.rand()
    child1 = alpha * parent1 + (1-alpha) * parent2
    child2 = (1-alpha) * parent1 + alpha * parent2
    return child1,child2

In [ ]:
Arithmetic_crossover(population[2],population[3])


(array([0.17004835, 0.19218167, 0.14013999, 0.24044002, 0.25718997]),
 array([0.16332816, 0.18983096, 0.15321492, 0.23792041, 0.25570555]))

In [ ]:
def next_generation(pop_size,elite,crossover=Heuristic_crossover):
    ''' Generates new population from elite population with mutation probability as 0.4 and crossover as 0.6.
        Over the final stages, mutation probability is decreased to 0.1.
        Input: Population Size and elite population.
        Output: Next generation population (2D Array).'''
    new_population=[]
    elite_range=range(len(elite))
#     print(elite_range)
    while len(new_population) < pop_size:
        if len(new_population) > 2*pop_size/3: # In the final stages mutation frequency is decreased.
            mutate_or_crossover = np.random.choice([0, 1], p=[0.9, 0.1])
        else:
            mutate_or_crossover = np.random.choice([0, 1], p=[0.4, 0.6])
#         print(mutate_or_crossover)
        if mutate_or_crossover:
            indx=np.random.choice(elite_range)
            new_population.append(mutation(elite[indx]))
        else:
            p1_idx,p2_idx=np.random.choice(elite_range,2)
            c1,c2=crossover(elite[p1_idx],elite[p2_idx])
            chk=0
            for gene in range(5):
                if c1[gene]<0:
                    chk+=1
                else:
                    chk+=0
            if (chk)>0:
                p1_idx,p2_idx=np.random.choice(elite_range,2)
                c1,c2=crossover(elite[p1_idx],elite[p2_idx])
            new_population.extend([c1,c2])
    return new_population

In [ ]:
elite=Select_elite_population(population)
print(len(elite))
next_generation(100,elite)[:3]

<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


30


[array([ 0.3148562 , -0.0530356 ,  0.30660858,  0.22504218,  0.20652863]),
 array([0.16259722, 0.21828913, 0.20727698, 0.15320139, 0.25863529]),
 array([0.0900034 , 0.01805285, 0.40112246, 0.16721411, 0.32360719])]

In [ ]:
elite=Select_elite_population(population)
next_generation(100,elite,Arithmetic_crossover)[:3]

<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


[array([0.39523768, 0.04280661, 0.4070629 , 0.13413701, 0.02075579]),
 array([0.1064532 , 0.27987871, 0.29638082, 0.02330907, 0.2939782 ]),
 array([0.16121526, 0.12387689, 0.38228044, 0.12622953, 0.20639788])]

In [ ]:
n=5# Number of stocks = 6
pop_size=100 # initial population = 100

# Initial population
population = np.array([chromosome(n) for _ in range(pop_size)])

# Get initial elite population
elite = Select_elite_population(population)

iteration=0
Expected_returns=0
Expected_risk=1

while (Expected_returns < 0.30 and Expected_risk > 0.0005) or iteration <= 40:
    print('Iteration:',iteration)
    population = next_generation(100,elite)
    elite = Select_elite_population(population)
    Expected_returns=mean_portfolio_return(elite[0])
    Expected_risk=var_portfolio_return(elite[0])
    print('Expected returns of {} with risk of {}\n'.format(Expected_returns,Expected_risk))
    iteration+=1


print('Portfolio of stocks after all the iterations:\n')
[print(hist_stock_returns.columns[i],':',elite[0][i]) for i in list(range(5))]

<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


Iteration: 0
Expected returns of 0.2670294849653511 with risk of 0.011613237303414294

Iteration: 1
Expected returns of 0.28100687609045877 with risk of 0.009848215359245415

Iteration: 2
Expected returns of 0.32381127108651764 with risk of 0.007268188385284044

Iteration: 3
Expected returns of 0.3880526836733562 with risk of 0.003992300770479521

Iteration: 4
Expected returns of 0.3377108277537807 with risk of 0.002610162907184757

Iteration: 5
Expected returns of 0.4200055395539398 with risk of 0.0009777668769330172

Iteration: 6
Expected returns of 0.38673824585459216 with risk of 0.0020943466186954043

Iteration: 7
Expected returns of 0.3645994342605387 with risk of 0.002000638191002005

Iteration: 8
Expected returns of 0.47132248859879877 with risk of 0.0014288000199264989

Iteration: 9
Expected returns of 0.5566992434815347 with risk of 0.0016858007579044626

Iteration: 10
Expected returns of 0.6055012222358609 with risk of 0.001775953834543778

Iteration: 11
Expected returns of 

[None, None, None, None, None]

In [ ]:
print('Portfolio of stocks after all the iterations:\n')
[print(hist_stock_returns.columns[i],':',elite[0][i]) for i in list(range(5))]

print('\nExpected returns of {} with risk of {}\n'.format(Expected_returns,Expected_risk))

Portfolio of stocks after all the iterations:

HDFCBANK.NS : -0.6077220418610169
INFY.NS : -3.730776367587304
ITC.NS : 1.3882201678905681
RELIANCE.NS : -1.3437338903281757
TCS.NS : 5.294012131885904

Expected returns of 1.132396867033179 with risk of 0.002748271802897273



In [ ]:
n=5 # Number of stocks = 6
pop_size=100 # initial population = 100

# Initial population
population = np.array([chromosome(n) for _ in range(pop_size)])

# Get initial elite population
elite = Select_elite_population(population)

iteration=0
Expected_returns=0
Expected_risk=1

while (Expected_returns < 0.30 and Expected_risk > 0.0005) or iteration <= 40 :
    print('Iteration:',iteration)
    if iteration==100:
        break
    population = next_generation(100,elite,Arithmetic_crossover)
    elite = Select_elite_population(population)
    Expected_returns=mean_portfolio_return(elite[0])
    Expected_risk=var_portfolio_return(elite[0])
    print('Expected returns of {} with risk of {}\n'.format(Expected_returns,Expected_risk))
    iteration+=1


print('Portfolio of stocks after all the iterations:\n')
[print(hist_stock_returns.columns[i],':',elite[0][i]) for i in list(range(5))]

Iteration: 0


<ipython-input-19-124350a5d4a5>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  temp=cov_hist_return.iloc[i][j] * child[i] * child[j]


Expected returns of 0.29020732227270196 with risk of 0.009529667262410719

Iteration: 1
Expected returns of 0.2895081333900364 with risk of 0.009544896519283506

Iteration: 2
Expected returns of 0.29146126325890487 with risk of 0.010066083064037838

Iteration: 3
Expected returns of 0.2872393932596111 with risk of 0.010009280554975818

Iteration: 4
Expected returns of 0.28500606964049846 with risk of 0.00990852381797891

Iteration: 5
Expected returns of 0.28829461486168745 with risk of 0.010272186354147303

Iteration: 6
Expected returns of 0.28404440398691333 with risk of 0.009712737951226697

Iteration: 7
Expected returns of 0.2808034422679958 with risk of 0.009336148024367108

Iteration: 8
Expected returns of 0.27973331009208746 with risk of 0.009212215882804946

Iteration: 9
Expected returns of 0.2798122680124299 with risk of 0.009221132817637926

Iteration: 10
Expected returns of 0.2799491807568491 with risk of 0.009236266018248656

Iteration: 11
Expected returns of 0.28035225090559

[None, None, None, None, None]

In [ ]:
print('Portfolio of stocks after all the iterations:\n')
[print(hist_stock_returns.columns[i],':',elite[0][i]) for i in list(range(5))]

print('\nExpected returns of {} with risk of {}\n'.format(Expected_returns,Expected_risk))

Portfolio of stocks after all the iterations:

HDFCBANK.NS : 0.1207095000088109
INFY.NS : 0.019769851154024
ITC.NS : 0.5751887749749256
RELIANCE.NS : 0.19059982083000082
TCS.NS : 0.09373205303223897

Expected returns of 0.28082329320518384 with risk of 0.009342309828009432

